name: Show Name Action
on:
  push:
    branches:
      - main

jobs:
  show_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Show Name
        run: |
          echo "Artyr"
          echo "Volunets"

